version: "3.8"

services:
  memcached:
    image: docker.io/library/memcached:1.6-alpine
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -v -m 256
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211 | grep evictions
      interval: 1m
      start_period: 1m
      timeout: 3s

  mariadb:
    image: docker.io/library/mariadb:11.1
    container_name: seafile-mariadb
    restart: unless-stopped
    env_file:
      - ./.mariadb.env
    volumes:
      - seafile-mariadb:/var/lib/mysql
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      interval: 1m
      start_period: 1m
      timeout: 5s

  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    restart: unless-stopped
    ports:
      - "127.0.0.1:61000:80"
    env_file:
      - ./.seafile.env
    volumes:
      - /opt/seafile-data:/shared
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    depends_on:
      - memcached
      - mariadb

volumes:
  seafile-mariadb: